// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHL6lahDOqsf5aEQVVb69HH-4EX26EH-o',
    appId: '1:424250873494:web:3118be03365ca8737d14b7',
    messagingSenderId: '424250873494',
    projectId: 'stocks-b8631',
    authDomain: 'stocks-b8631.firebaseapp.com',
    storageBucket: 'stocks-b8631.firebasestorage.app',
    measurementId: 'G-3F3096PY25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zHwDEu8Q7DVA7j3lNwDkuHLyibqb-FI',
    appId: '1:424250873494:android:c3db4254715ab3247d14b7',
    messagingSenderId: '424250873494',
    projectId: 'stocks-b8631',
    storageBucket: 'stocks-b8631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJDlLNvGhM_K-6hr6kP-uzw9wrn2r2LY',
    appId: '1:424250873494:ios:27f105b169b454927d14b7',
    messagingSenderId: '424250873494',
    projectId: 'stocks-b8631',
    storageBucket: 'stocks-b8631.firebasestorage.app',
    iosBundleId: 'com.Hheis.stocks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJDlLNvGhM_K-6hr6kP-uzw9wrn2r2LY',
    appId: '1:424250873494:ios:27f105b169b454927d14b7',
    messagingSenderId: '424250873494',
    projectId: 'stocks-b8631',
    storageBucket: 'stocks-b8631.firebasestorage.app',
    iosBundleId: 'com.Hheis.stocks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHL6lahDOqsf5aEQVVb69HH-4EX26EH-o',
    appId: '1:424250873494:web:43bfd8bd4392f3857d14b7',
    messagingSenderId: '424250873494',
    projectId: 'stocks-b8631',
    authDomain: 'stocks-b8631.firebaseapp.com',
    storageBucket: 'stocks-b8631.firebasestorage.app',
    measurementId: 'G-377F6WCDRK',
  );
}
